$(".more2").on("click",function(){
    $('.contentsofmovie2').toggleClass("show");
    $('.more2').toggleClass("hide");
    $('.close2').toggleClass("show")
})
$(".close2").on("click",function(){
    $('.contentsofmovie2').toggleClass("show");
    $('.more2').toggleClass("hide");
    $('.close2').toggleClass("show")
})
